"""Render the normalized config tables back into `settings.yaml` text.

This is the other half of the seam. `pipeline.build_context(settings_text=...)` takes
a YAML **string** and parses it with `yaml.safe_load` into a plain dict
(`src/pipeline.py:184`, `src/config.py:17-29`), so a database-backed config only has
to produce that string. `src/` never learns about Postgres, the I/O-boundary
allowlist is unchanged, and `service/` stays deletable.

**Byte-stability is a hard requirement, not a nicety.** `config_versions` is
content-addressed on sha256, so a renderer whose output wobbled — dict ordering, a
float repr, a trailing space — would mint a fresh "version" on every render, break
pin de-duplication, and make "did the config change?" unanswerable. Every query here
carries an explicit ORDER BY, and every value is emitted through `yaml.safe_dump` so
quoting and escaping are decided by one library rather than by string formatting.

**Every key is emitted explicitly, including the ones whose absence would be
dangerous.** `dedupe_rows` has a code default that is the OPPOSITE of its configured
value — it defaults to True, which silently drops legitimate duplicate order lines
and understates revenue. "Key absent" is therefore not a safe state, and
`assert_complete` exists so a missing row fails a test rather than a settlement run.
(`drop_unmapped_columns` was the second such key until M8/2.4 flipped its code
default to True; it is still required, but its absence no longer leaks.)

**On comments.** Top-level evidence is re-emitted as a comment block above its key,
so the rendered file still reads like the hand-written one. Per-entry evidence — the
justification for one alias, one column-map spelling — lives in its row's `evidence`
column and is served to the editor from there (`service/config_rows.py`). The
comment was always a lossy carrier for something that wanted to be a field, which is
why removing one entry could leave the block documenting another captioning its
neighbour — a failure mode the M6 editor had to model and 1.6 deleted along with the
module that modelled it. The rendered file is a derived artifact for humans and for
the pipeline; the rows are the evidence store.
"""

from __future__ import annotations

from typing import Any

import yaml

# The order top-level keys appear in the rendered file. Fixed here rather than
# derived, because this is the reading order of a document somebody maintains: the
# money model first, then how files are found and read, then who the stores are.
KEY_ORDER = (
    "vat_factors", "invoice_buckets", "fee_buckets",
    "masters_file", "reader_engine", "tolerances",
    "window_settlement_bounds", "number_style", "numeric_coercion",
    "drop_unmapped_columns", "dedupe_rows", "cross_window_order_backfill",
    "dayfirst", "date_formats",
    "skip_rows_after_header",
    "file_formats", "sheet_names", "sheet_patterns", "header_rows",
    "store_from_filename", "stores_optional", "expected_stores", "store_to_brand",
    "store_aliases", "column_maps",
)

HEADER = """\
# settings.yaml — the domain contract, RENDERED from the config_* tables.
#
# Do not hand-edit a deployed copy: this file is generated by
# service/config_render.py and regenerated whenever the configuration changes, so
# an edit here is overwritten. The editable copy is the database; the CLI path
# reads this file, and `python -m service.admin config export` refreshes it.
#
# The committed copy in git is the SEED — what a fresh deployment imports from
# before anything has been edited (service/config_import.py).
"""


def _dump(key: str, value: Any) -> str:
    """One top-level key as YAML. `safe_dump` owns all quoting and escaping."""
    return yaml.safe_dump({key: value}, sort_keys=False, allow_unicode=True,
                          default_flow_style=False, width=10_000)


def _comment(evidence: str) -> str:
    if not evidence.strip():
        return ""
    lines = []
    for line in evidence.splitlines():
        line = line.rstrip()
        # Evidence lifted from the file already carries its "# ". Text typed into
        # the editor does not, so both shapes have to render identically.
        lines.append(line if line.startswith("#") else (f"# {line}" if line else "#"))
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Reading the tables
# ---------------------------------------------------------------------------

def read_config(conn) -> tuple[dict[str, Any], dict[str, str]]:
    """Returns (settings mapping, per-top-level-key evidence).

    One function so the ORDER BY clauses that make rendering deterministic live in
    exactly one place.
    """
    values: dict[str, Any] = {}
    evidence: dict[str, str] = {}

    with conn.cursor() as cur:
        # --- scalars -------------------------------------------------------
        cur.execute("select key, value, evidence from config_scalars order by sort_order")
        for key, value, ev in cur.fetchall():
            # psycopg decodes jsonb into Python objects already: a jsonb string
            # arrives as `str`, a jsonb array as `list`. Nothing to parse here, and
            # a json.loads() would choke on the string case.
            parsed = value
            if "." in key:
                parent, child = key.split(".", 1)
                values.setdefault(parent, {})[child] = parsed
                evidence.setdefault(parent, ev or "")
            else:
                values[key] = parsed
                evidence[key] = ev or ""

        # --- per-platform --------------------------------------------------
        cur.execute("""select platform, dayfirst, store_from_filename, evidence
                       from config_platforms order by sort_order, platform""")
        for platform, dayfirst, pattern, ev in cur.fetchall():
            # NULL means the platform's reader does not consume it, so emitting
            # anything would be config nothing reads (migration 009).
            if dayfirst is not None:
                values.setdefault("dayfirst", {})[platform] = bool(dayfirst)
            if pattern:
                values.setdefault("store_from_filename", {})[platform] = pattern
                evidence.setdefault("store_from_filename", ev or "")

        # --- per-platform/kind reading rules -------------------------------
        # One row fans back out into the five sibling maps the pipeline reads.
        cur.execute("""select platform, kind, sheet_name, sheet_pattern, header_row,
                              skip_rows_after_header, reader_engine, date_format, evidence
                       from config_reading order by sort_order, platform, kind""")
        for platform, kind, name, pattern, header, skip, engine, date_fmt, ev in cur.fetchall():
            if date_fmt:
                values.setdefault("date_formats", {}).setdefault(platform, {})[kind] = date_fmt
                evidence.setdefault("date_formats", ev or "")
            if name:
                values.setdefault("sheet_names", {}).setdefault(platform, {})[kind] = name
            if pattern:
                values.setdefault("sheet_patterns", {}).setdefault(platform, {})[kind] = pattern
            if header and int(header) != 1:
                values.setdefault("header_rows", {}).setdefault(platform, {})[kind] = int(header)
            if skip and int(skip) != 0:
                values.setdefault("skip_rows_after_header", {}).setdefault(platform, {})[kind] = int(skip)
            if engine:
                values.setdefault("reader_engine", {}).setdefault(platform, {})[kind] = engine
                evidence.setdefault("reader_engine", ev or "")

        # --- column maps ---------------------------------------------------
        # Inactive rows are a retired header SPELLING, kept for provenance. They are
        # not emitted: read_parts would happily match one, and a run pointed at a
        # current export should not resolve a header the platform stopped writing.
        cur.execute("""select platform, kind, raw_header, canonical
                       from config_column_maps where active
                       order by sort_order, platform, kind, raw_header""")
        for platform, kind, raw, canonical in cur.fetchall():
            values.setdefault("column_maps", {}).setdefault(platform, {}) \
                  .setdefault(kind, {})[raw] = canonical

        # --- stores --------------------------------------------------------
        cur.execute("""select platform, store, optional, evidence from config_stores
                       where active order by sort_order, platform, store""")
        for platform, store, optional, ev in cur.fetchall():
            values.setdefault("expected_stores", {}).setdefault(platform, []).append(store)
            if optional:
                values.setdefault("stores_optional", {}).setdefault(platform, []).append(store)
            evidence.setdefault("expected_stores", ev or "")

        # --- aliases -------------------------------------------------------
        # A NULL canonical means unresolved. It renders as the TODO-HUMAN sentinel
        # the pipeline still recognises, so ingest keeps warning about it; the
        # database models it honestly as "no decision" either way.
        cur.execute("""select platform, raw, canonical, evidence
                       from config_store_aliases order by sort_order, platform, raw""")
        for platform, raw, canonical, ev in cur.fetchall():
            values.setdefault("store_aliases", {}).setdefault(platform, {})[raw] = (
                canonical if canonical is not None else "TODO-HUMAN")
            evidence.setdefault("store_aliases", ev or "")

        # --- store -> brand ------------------------------------------------
        # ONLY rows flagged as part of the pipeline contract. The 60 rows imported
        # from brand_map.csv are held here for the month-end master and are
        # deliberately NOT rendered: emitting them would change the brand of 28
        # stores, which is a behaviour change and not something a config migration
        # gets to do quietly (migration 007, `in_pipeline_contract`).
        #
        # `store_to_brand` is flat (store -> brand), so a store selling under one
        # brand on two platforms collapses to one entry. That is the pipeline's own
        # shape (`ingest.derive_brand`), not something introduced here.
        cur.execute("""select store, brand from config_store_brands
                       where in_pipeline_contract
                       order by sort_order, platform, store""")
        brands = {store: brand for store, brand in cur.fetchall()}
        # Always emitted, even when empty: `derive_brand` warns loudly on an empty
        # map, and that warning is a real signal (D12) that must not disappear
        # because a key stopped being rendered.
        values["store_to_brand"] = brands

        # --- tolerances ----------------------------------------------------
        cur.execute("""select platform, name, vnd, evidence from config_tolerances
                       order by sort_order, platform, name""")
        for platform, name, vnd, ev in cur.fetchall():
            number = float(vnd)
            emit = int(number) if number == int(number) else number
            target = values.setdefault("tolerances", {})
            if platform:
                target.setdefault(platform, {})[name] = emit
            else:
                target[name] = emit
            evidence.setdefault("tolerances", ev or "")

        # --- invoice buckets -------------------------------------------------
        # The NULL-needle row is the catch-all and renders as `default`; the rest
        # render as `match` in sort_order, which is walk order and therefore
        # meaning (first matching needle wins).
        cur.execute("""select platform, needle, bucket, evidence
                       from config_invoice_buckets
                       order by sort_order, platform, needle""")
        for platform, needle, bucket, ev in cur.fetchall():
            node = values.setdefault("invoice_buckets", {}).setdefault(platform, {})
            if needle is None:
                node["default"] = bucket
            else:
                node.setdefault("match", {})[needle] = bucket
            evidence.setdefault("invoice_buckets", ev or "")

        # --- fee bucket roles ------------------------------------------------
        cur.execute("""select platform, role, bucket, evidence
                       from config_fee_buckets
                       order by sort_order, platform, role, bucket""")
        for platform, role, bucket, ev in cur.fetchall():
            node = values.setdefault("fee_buckets", {}).setdefault(platform, {})
            if role == "revenue":
                node["revenue"] = bucket
            else:
                node.setdefault("promo", []).append(bucket)
            evidence.setdefault("fee_buckets", ev or "")

        # --- settlement bounds ---------------------------------------------
        cur.execute("""select period, from_date, to_date, evidence
                       from config_settlement_bounds order by sort_order, period""")
        for period, start, end, ev in cur.fetchall():
            bounds: dict[str, str] = {}
            if start:
                bounds["from"] = start.isoformat()
            if end:
                bounds["to"] = end.isoformat()
            values.setdefault("window_settlement_bounds", {})[period] = bounds
            evidence.setdefault("window_settlement_bounds", ev or "")

    return values, evidence


def render(conn) -> str:
    """The whole file, as text."""
    values, evidence = read_config(conn)
    out = [HEADER]
    for key in KEY_ORDER:
        if key not in values:
            continue
        out.append("")
        block = _comment(evidence.get(key, ""))
        if block:
            out.append(block.rstrip("\n"))
        out.append(_dump(key, values[key]).rstrip("\n"))
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# The completeness control
# ---------------------------------------------------------------------------

# Keys `src/` reads with a default that differs from the configured value. A missing
# row here does not raise — it silently changes money or leaks PII.
DANGEROUS_DEFAULTS = {
    "dedupe_rows": "code default is True — legitimate duplicate order lines "
                   "would be dropped and revenue understated",
}

# `drop_unmapped_columns` was in the map above until M8/2.4, when `src/ingest.py`'s
# default flipped False -> True. Its absence no longer leaks PII, so it is no longer
# DANGEROUS — but it stays in REQUIRED_KEYS below, because a config that does not
# state its PII posture is a config nobody can audit, and this file is the audit.

# Everything the pipeline reads that must be present in a rendered config.
REQUIRED_KEYS = (
    "vat_factors", "masters_file", "tolerances", "number_style",
    "numeric_coercion", "drop_unmapped_columns", "dedupe_rows", "file_formats",
    "store_from_filename", "expected_stores", "column_maps",
    # A14 (2026-08-20): the bucket lists and the rate list moved out of code with
    # hard-stop accessors, so a rendered config without them cannot build a
    # workbook — absence should fail here, in a test, not in a settlement run.
    "invoice_buckets", "fee_buckets",
    # Absent means `off`, which is the SAFE direction (today's behaviour, and every
    # golden was produced under it) — so this is not a DANGEROUS_DEFAULT. It is
    # required anyway, for the reason `drop_unmapped_columns` is: a contract that
    # does not state whether it borrows lines across windows is a contract nobody
    # can audit, and stating it is what this file is for.
    "cross_window_order_backfill",
)


def assert_complete(settings: dict) -> None:
    """Raise unless a rendered config supplies every key the pipeline reads.

    The audit that produced this found the failure mode it defends against: two
    flags whose code default is the opposite of their configured value, so "the row
    is missing" and "the row says false" are indistinguishable at the call site and
    only one of them is safe. Being explicit is the whole point of rendering rather
    than relying on `settings.get(key, default)`.
    """
    missing = [k for k in REQUIRED_KEYS if k not in settings]
    if missing:
        detail = "; ".join(
            f"{k} ({DANGEROUS_DEFAULTS[k]})" if k in DANGEROUS_DEFAULTS else k
            for k in missing)
        raise ValueError(
            f"rendered config is missing {len(missing)} key(s) the pipeline reads: "
            f"{detail}")
